### ISSUE TITLE
Using the observer based approach randomly fails with CardRequestTimeoutException

### ISSUE THREAD

**Issue by knedlsepp** [LudovicRousseau/pyscard#64] opened 2018-08-16 10:18 UTC
I've been using the [sample_TransmitCardObserver.py](https://github.com/LudovicRousseau/pyscard/blob/aea375e4ecc8486cb810d1754f9e9668845c9343/smartcard/Examples/framework/sample_TransmitCardObserver.py) example for reading mifare-tags. I do want to run this script as a daemon, but I'm getting random `CardRequestTimeoutException: Time-out during card request` errors.
Those keep mostly popping up, when quickly interacting with the reader and the tag - putting it to the reader only for a short time and pulling it away.
The full trace is as follows:

```
Traceback (most recent call last):
  File "lib/python3.6/site-packages/smartcard/CardMonitoring.py", line 160, in run
    currentcards = self.cardrequest.waitforcardevent()
  File "lib/python3.6/site-packages/smartcard/CardRequest.py", line 72, in waitforcardevent
    return self.pcsccardrequest.waitforcardevent()
  File "lib/python3.6/site-packages/smartcard/pcsc/PCSCCardRequest.py", line 309, in waitforcardevent
    raise CardRequestTimeoutException()
smartcard.Exceptions.CardRequestTimeoutException: Time-out during card request
```

After this happens the program just hangs indefinitely.
I tracked the issue down to: https://github.com/LudovicRousseau/pyscard/pull/22
Without this PR, the Monitor just keeps on going, printing the occasional stack-trace, but otherwise seeming to work fine.
I'm now using `pyscard` exclusively with this patch locally undone. I would however love to see this fixed here. I guess for now I'd prefer for #22 to be un-merged. If the only downside of that is "duplicate error message printouts" not being prevented, I would prefer the monitoring-thread not being stopped on a `CardRequestTimeoutException` and mostly working flawlessly otherwise.

**Comment by LudovicRousseau** [comment] 2018-08-27 12:46
What operating system are you using?

**Comment by knedlsepp** [comment] 2018-08-27 14:51
I've had this issue on macOS.

**Comment by LudovicRousseau** [comment] 2018-08-27 14:55
What version of macOS?

**Comment by knedlsepp** [comment] 2018-08-27 15:00
I'm running 10.11.6.

**Comment by knedlsepp** [comment] 2018-08-27 21:30
I'm also experiencing the same problem on a Raspberry pi 3B+ running NixOS-18.03 and using pcsclite and the CCID driver.

**Comment by LudovicRousseau** [comment] 2018-08-28 08:19
Good to know the problem is not related to macOS but is also present on GNU/Linux + pcsclite.
Do you also have the problem with contact cards? or only with contactless cards?

**Comment by knedlsepp** [comment] 2018-08-28 08:50
Sadly the ACR122U is the only reader I own.

**Comment by knedlsepp** [comment] 2018-09-07 11:32
Great to hear!

**Comment by LudovicRousseau** [comment] 2018-09-07 14:10
Fixed in https://github.com/LudovicRousseau/pyscard/commit/2bd0b0fd0d464483374663282602e02d54715e4f

**Closed by LudovicRousseau** 2018-09-07 14:10 UTC
