### ISSUE TITLE
pyscard 1.9.1 and py2exe

### ISSUE THREAD

**Issue by MrJeanDenis** [LudovicRousseau/pyscard#16] opened 2015-10-20 21:24 UTC
Hello,

I have a script which works fine using Pyscard 1.9.1 with Python 3.4.3 on Windows 7. Py2exe generates an EXE file from my script, no error or warning are reported by Py2exe during generation but when I run the EXE file, I get this error:
```python
  File "C:\Python34\lib\site-packages\smartcard\scard\scard.py", line 121, in swig_import_helper
    import _scard
ImportError: No module named '_scard'
```
I face the same issue when I want to build EXE file for Py2exe examples provided with Pyscard 1.6.12

What causes this error? How can I create EXE files using Pyscard?

Thank you for your help.

**Comment by LudovicRousseau** [comment] 2015-10-21 11:23
If your script works fine using PySCard 1.9.1 then the problem is not within PySCard.

Maybe Py2exe does not work with modules using SWIG. You should ask for support from the Py2exe project.

**Comment by LudovicRousseau** [comment] 2015-11-22 17:51
It must be a Py2exe problem.
Closing.

**Closed by LudovicRousseau** 2015-11-22 17:51 UTC
